<MyButton@Button>:
	size_hint:[None,None]
	size:[100,100]
	
<MyAnchor>:
	rows:3
	AnchorLayout:
		anchor_x:'left'
		anchor_y:'top'
		canvas:
			Color:
				rgb:[1,0,0]
			Rectangle:
				pos:self.pos
				size:self.size
				
		MyButton:
			text:'b1'		
			
	AnchorLayout:
		anchor_x:'center'
		anchor_y:'top'
		canvas:
			Color:
				rgb:[0,1,0]
			Rectangle:
				pos:self.pos
				size:self.size
				
		MyButton:
			text:'b2'					